[build]
  command = "npm run build" # This will run both next build and next export
  publish = "out"
  functions = "out/functions" # Only if using API routes

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" # Match your local Node version